@REM ipes_cnn_rgb
python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt
python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml --model.init_args.name ipes_cnn_rgb --trainer.default_root_dir models/ipes_cnn_rgb --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_cnn_rgb/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_cnn
@REM python ipes.py fit -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn
python ipes.py test -c configs/ipes_cnn.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml --model.init_args.name ipes_cnn --trainer.default_root_dir models/ipes_cnn --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_cnn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_cnn_colorizer
@REM python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_colorizer.yaml --model.init_args.name ipes_cnn_colorizer --trainer.default_root_dir models/ipes_cnn_colorizer --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_cnn_colorizer/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_cnn_only_nn
@REM python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_nn.yaml --model.init_args.name ipes_cnn_only_nn --trainer.default_root_dir models/ipes_cnn_only_nn --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_cnn_only_nn/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_cnn_only_lin
@REM python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_only_lin.yaml --model.init_args.name ipes_cnn_only_lin --trainer.default_root_dir models/ipes_cnn_only_lin --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_cnn_only_lin/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_dctnet
@REM python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_dctnet.yaml --model.init_args.name ipes_dctnet --trainer.default_root_dir models/ipes_dctnet --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_dctnet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_cnn_allstar
@REM python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_cnn_allstar.yaml --model.init_args.name ipes_cnn_allstar --trainer.default_root_dir models/ipes_cnn_allstar --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_cnn_allstar/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_unet
@REM python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_unet.yaml --model.init_args.name ipes_unet --trainer.default_root_dir models/ipes_unet --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_unet/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_rast
@REM python ipes.py fit -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt
python ipes.py test -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0
@REM python ipes.py predict -c configs/ipes_cnn.yaml -c configs/ipes_cnn_rgb.yaml -c configs/ipes_rast.yaml --model.init_args.name ipes_rast --trainer.default_root_dir models/ipes_rast --data.init_args.in_file datasets/laz_minimal/bins/ahn5/chunkPoints.csv --ckpt_path models/ipes_rast/alpha/checkpoints/last.ckpt --trainer.logger False --data.init_args.workers 0

@REM ipes_interp_rast_hqsplat_mean
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean]
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --trainer.logger False --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean] --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --trainer.logger False --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean] --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --trainer.logger False --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean] --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --trainer.logger False --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean] --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --trainer.logger False --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean] --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --trainer.logger False --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean] --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_rast_hqsplat_mean --trainer.logger False --data.init_args.pts_to_img_methods [rast_hqsplat_mean] --data.init_args.rgb_to_img_methods [rast_hqsplat_mean] --model.init_args.name ipes_interp_rast_hqsplat_mean --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv

@REM ipes_interp_linear
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear]
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --trainer.logger False --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear] --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --trainer.logger False --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear] --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --trainer.logger False --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear] --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --trainer.logger False --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear] --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --trainer.logger False --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear] --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --trainer.logger False --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear] --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_linear --trainer.logger False --data.init_args.pts_to_img_methods [linear] --data.init_args.rgb_to_img_methods [linear] --model.init_args.name ipes_interp_linear --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv

@REM ipes_interp_cubic
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/test_ca_13.txt --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/test_swisssurface3d.txt --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/test_ID15_Bunds.txt --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/test_Bund_BoraPk.txt --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BF44.txt --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_0to23.txt --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic]
python ipes_interp.py test -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/test_NZ23_Gisborne_subsets_BG41_24to50.txt --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic]
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --trainer.logger False --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic] --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/bins/ca_13/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --trainer.logger False --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic] --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/bins/swisssurface3d/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --trainer.logger False --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic] --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/bins/ID15_Bunds/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --trainer.logger False --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic] --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/bins/Bund_BoraPk/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --trainer.logger False --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic] --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BF44/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --trainer.logger False --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic] --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_0to23/chunkPoints.csv
@REM python ipes_interp.py predict -c configs/ipes_interp.yaml --trainer.default_root_dir models/ipes_interp_cubic --trainer.logger False --data.init_args.pts_to_img_methods [cubic] --data.init_args.rgb_to_img_methods [cubic] --model.init_args.name ipes_interp_cubic --data.init_args.in_file datasets/laz_minimal/bins/NZ23_Gisborne_subsets_BG41_24to50/chunkPoints.csv


@REM E:\repos_ssd\simlod\build\Release\CreateTraining.exe