data:
  init_args:
    rgb_to_img_methods:
    - 'nearest'
    - 'linear'

model:
  init_args:
    has_color_input: False
    has_color_output: True
    output_names:
      - 'hm_val'
      - 'hm_rgb'