data:
  init_args:
    hm_interp_size: 96
    hm_size: 64
    meters_per_pixel: 10.0
    rgb_to_img_methods:
    - 'linear'
    pts_to_img_methods:
    - 'nearest'
    - 'linear'

model:
  init_args:
    has_color_input: False
    has_color_output: False
