model:
  class_path: source.modules.ipes_dctnet.IpesDCTNet
  init_args:
    name: 'ipes'
    results_dir: 'results'
    predict_batch_size: 100
    network_latent_size: 128
    use_mlp: True
    mlp_layers: 1
    dropout: 0.0
